### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by stefreak** [syseleven/heattemplates-examples#8]

**Comment by jpeschkeSys11** [comment]
What license would you recommend?

**Comment by stefreak** [comment]
@jpeschkeSys11 I'd recommend using the MIT license because it's simple and permissive.

See also https://choosealicense.com/

**Comment by dschwabeS11** [comment]
Can we just add the MIT license or do we have to watch out for something specific?

**Comment by stefreak** [comment]
I'm pro MIT license

**Comment by jpeschkeSys11** [comment]
addedMIT License file
